### ISSUE TITLE
want py

### ISSUE THREAD

**Issue by Zwlin98** [Meowcolm024/lost-avalon#4]
where does this idea come from？I think it is a very great program. by the way, I am also playing fgo, can you give me your py code? you can email me,cause I could not find your contacts on GitHub.when the exam finish, please allow me to participate your another project,fgo-automate.that also a project i really want to join.

**Comment by Meowcolm024** [comment]
You can try to raise `issues` in there or directly join the project and create `pull request`
直接参与就好了啊owo

**Comment by Zwlin98** [comment]
OK
